name: cbt_tpa_fic17_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.9
  # go_router: ^13.0.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  mobile_scanner: ^5.1.0
  qr_flutter: ^4.1.0
  timer_count_down: ^2.2.2
  http: ^1.2.1
  dartz: ^0.10.1
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  connectivity_plus: ^6.0.3
  # print_bluetooth_thermal: ^1.1.0
  esc_pos_utils_plus: ^2.0.3
  #
  #
  #
  #
  #
  #
  cupertino_icons: ^1.0.6

dev_dependencies:
  freezed: ^2.5.2
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/nav/
    - assets/icons/payment/
    - assets/icons/settings/
flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true
# dependency_overrides:
#   print_bluetooth_thermal:
#     git:
#       url: https://github.com/kakzaki/print_bluetooth_thermal.git

# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages

# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
